rpc:
  address: ":8902"
  max_body_bytes: 1048576
  max_batch_size: 32

log:
  level: "info"
  format: "json"
  add_source: false
  output: "file"
  file_path: "./logs/prod/solana_golang.log"

database:
  engine: "pebble"
  path: "./data/p2p-test/prod"
  wal: true

p2p:
  ip_type: "ip4"
  listen_ip: "0.0.0.0"
  advertised_ip: "127.0.0.1"
  advertised_port: 5005
  listen_port: 5005
  default_protocol: "quic"
  max_peers: 64
  network_id: "solana_golang:p2p-test:00000000000000000000000000000000"
  software_version: "solana_golang/0.1.0"
  min_outbound_peers: 1
  bootstrap_timeout_millis: 5000
  bootstrap:
    - "/ip4/127.0.0.1/quic/5002/p2p/6o26fjDM19ZgdMzSmucpqeC49ggmWEDYRcGiiPA7RxVk"
