rpc:
  address: ":8899"
  max_body_bytes: 1048576
  max_batch_size: 32

log:
  level: "info"
  format: "json"
  add_source: false
  output: "console"
  file_path: "./logs/demo/solana_golang.log"

database:
  engine: "pebble"
  path: "./data/pebble"
  wal: true

p2p:
  ip_type: "ip4"
  listen_ip: "0.0.0.0"
  listen_port: 5002
  default_protocol: "tcp"
  max_peers: 64
  network_id: "solana_golang:demo:00000000000000000000000000000000"
  software_version: "solana_golang/0.1.0"
  min_outbound_peers: 8
  bootstrap_timeout_millis: 5000
  bootstrap:
    - '/ip4/101.35.87.31/quic/8333/p2p/CCQ24R48twy4erGc8bkmDD2XtXeR3u33uPWRpBuAPcdA'
