rpc:
  address: ":8899"
  max_body_bytes: 1048576
  max_batch_size: 32

log:
  level: "info"
  format: "json"
  add_source: false
  output: "console"
  file_path: "./logs/local/solana_golang.log"

database:
  engine: "pebble"
  path: "./data/pebble"
  wal: true

p2p:
  peer_id: "11111111111111111111111111111111"
  ip_type: "ip4"
  listen_ip: "0.0.0.0"
  listen_port: 5002
  default_protocol: "tcp"
  max_peers: 64
