// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: p2p/proto/message.proto

package p2pproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageFlag int32

const (
	MessageFlag_MESSAGE_FLAG_UNKNOWN  MessageFlag = 0
	MessageFlag_MESSAGE_FLAG_NOTIFY   MessageFlag = 1
	MessageFlag_MESSAGE_FLAG_REQUEST  MessageFlag = 2
	MessageFlag_MESSAGE_FLAG_RESPONSE MessageFlag = 3
)

// Enum value maps for MessageFlag.
var (
	MessageFlag_name = map[int32]string{
		0: "MESSAGE_FLAG_UNKNOWN",
		1: "MESSAGE_FLAG_NOTIFY",
		2: "MESSAGE_FLAG_REQUEST",
		3: "MESSAGE_FLAG_RESPONSE",
	}
	MessageFlag_value = map[string]int32{
		"MESSAGE_FLAG_UNKNOWN":  0,
		"MESSAGE_FLAG_NOTIFY":   1,
		"MESSAGE_FLAG_REQUEST":  2,
		"MESSAGE_FLAG_RESPONSE": 3,
	}
)

func (x MessageFlag) Enum() *MessageFlag {
	p := new(MessageFlag)
	*p = x
	return p
}

func (x MessageFlag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageFlag) Descriptor() protoreflect.EnumDescriptor {
	return file_p2p_proto_message_proto_enumTypes[0].Descriptor()
}

func (MessageFlag) Type() protoreflect.EnumType {
	return &file_p2p_proto_message_proto_enumTypes[0]
}

func (x MessageFlag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageFlag.Descriptor instead.
func (MessageFlag) EnumDescriptor() ([]byte, []int) {
	return file_p2p_proto_message_proto_rawDescGZIP(), []int{0}
}

type P2PMessage struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Version            uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Id                 string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Type               uint32                 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	FromPeerId         string                 `protobuf:"bytes,4,opt,name=from_peer_id,json=fromPeerId,proto3" json:"from_peer_id,omitempty"`
	ToPeerId           string                 `protobuf:"bytes,5,opt,name=to_peer_id,json=toPeerId,proto3" json:"to_peer_id,omitempty"`
	RequestId          string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Flag               MessageFlag            `protobuf:"varint,7,opt,name=flag,proto3,enum=p2p.proto.MessageFlag" json:"flag,omitempty"`
	Payload            []byte                 `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	CreatedAtUnixMilli int64                  `protobuf:"varint,9,opt,name=created_at_unix_milli,json=createdAtUnixMilli,proto3" json:"created_at_unix_milli,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *P2PMessage) Reset() {
	*x = P2PMessage{}
	mi := &file_p2p_proto_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PMessage) ProtoMessage() {}

func (x *P2PMessage) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PMessage.ProtoReflect.Descriptor instead.
func (*P2PMessage) Descriptor() ([]byte, []int) {
	return file_p2p_proto_message_proto_rawDescGZIP(), []int{0}
}

func (x *P2PMessage) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *P2PMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *P2PMessage) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *P2PMessage) GetFromPeerId() string {
	if x != nil {
		return x.FromPeerId
	}
	return ""
}

func (x *P2PMessage) GetToPeerId() string {
	if x != nil {
		return x.ToPeerId
	}
	return ""
}

func (x *P2PMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *P2PMessage) GetFlag() MessageFlag {
	if x != nil {
		return x.Flag
	}
	return MessageFlag_MESSAGE_FLAG_UNKNOWN
}

func (x *P2PMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *P2PMessage) GetCreatedAtUnixMilli() int64 {
	if x != nil {
		return x.CreatedAtUnixMilli
	}
	return 0
}

var File_p2p_proto_message_proto protoreflect.FileDescriptor

const file_p2p_proto_message_proto_rawDesc = "" +
	"\n" +
	"\x17p2p/proto/message.proto\x12\tp2p.proto\"\xa2\x02\n" +
	"\n" +
	"P2PMessage\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x03 \x01(\rR\x04type\x12 \n" +
	"\ffrom_peer_id\x18\x04 \x01(\tR\n" +
	"fromPeerId\x12\x1c\n" +
	"\n" +
	"to_peer_id\x18\x05 \x01(\tR\btoPeerId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\x12*\n" +
	"\x04flag\x18\a \x01(\x0e2\x16.p2p.proto.MessageFlagR\x04flag\x12\x18\n" +
	"\apayload\x18\b \x01(\fR\apayload\x121\n" +
	"\x15created_at_unix_milli\x18\t \x01(\x03R\x12createdAtUnixMilli*u\n" +
	"\vMessageFlag\x12\x18\n" +
	"\x14MESSAGE_FLAG_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13MESSAGE_FLAG_NOTIFY\x10\x01\x12\x18\n" +
	"\x14MESSAGE_FLAG_REQUEST\x10\x02\x12\x19\n" +
	"\x15MESSAGE_FLAG_RESPONSE\x10\x03B\"Z solana_golang/p2p/proto;p2pprotob\x06proto3"

var (
	file_p2p_proto_message_proto_rawDescOnce sync.Once
	file_p2p_proto_message_proto_rawDescData []byte
)

func file_p2p_proto_message_proto_rawDescGZIP() []byte {
	file_p2p_proto_message_proto_rawDescOnce.Do(func() {
		file_p2p_proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_p2p_proto_message_proto_rawDesc), len(file_p2p_proto_message_proto_rawDesc)))
	})
	return file_p2p_proto_message_proto_rawDescData
}

var file_p2p_proto_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_p2p_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_p2p_proto_message_proto_goTypes = []any{
	(MessageFlag)(0),   // 0: p2p.proto.MessageFlag
	(*P2PMessage)(nil), // 1: p2p.proto.P2PMessage
}
var file_p2p_proto_message_proto_depIdxs = []int32{
	0, // 0: p2p.proto.P2PMessage.flag:type_name -> p2p.proto.MessageFlag
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_p2p_proto_message_proto_init() }
func file_p2p_proto_message_proto_init() {
	if File_p2p_proto_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_p2p_proto_message_proto_rawDesc), len(file_p2p_proto_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_p2p_proto_message_proto_goTypes,
		DependencyIndexes: file_p2p_proto_message_proto_depIdxs,
		EnumInfos:         file_p2p_proto_message_proto_enumTypes,
		MessageInfos:      file_p2p_proto_message_proto_msgTypes,
	}.Build()
	File_p2p_proto_message_proto = out.File
	file_p2p_proto_message_proto_goTypes = nil
	file_p2p_proto_message_proto_depIdxs = nil
}
